# ~/.config/sway/swaybar/colors.conf
colors {
    background #1d2021
    statusline #ebdbb2
    separator  #928374

    focused_workspace  #689d6a #689d6a #1d2021
    active_workspace   #1d2021 #1d2021 #928374
    inactive_workspace #1d2021 #1d2021 #928374
    urgent_workspace   #fb4934 #fb4934 #ebdbb2
}
