[main]
font=JetBrainsMono Nerd Font:size=12
prompt="❯  "
terminal=foot

lines=10
width=25
tabs=4
horizontal-pad=20
vertical-pad=15
inner-pad=8

[colors]
background=1d2021e6     
text=ebdbb2ff             
prompt=83a598ff           
input=ebdbb2ff

# Active row highlight layout (Matches your focused workspace bar structure)
selection=282828ff        
selection-text=689d6aff   
selection-match=fabd2fff  

# Border accent
border=689d6aff

[border]
width=2
radius=0
