# --- Foot Terminal Config ---

# Font and Padding

font=JetBrains Mono:size=12
pad=20x20                             

[colors]
# Bump alpha to 0.90 if 0.85 was too "busy" with the wallpaper
alpha= 0.90
background=1d2021
foreground=ebdbb2

# Fix for the deprecated cursor color error
cursor=1d2021 ebdbb2 

## Gruvbox Dark Palette
regular0=262626  # black
regular1=cc241d  # red
regular2=98971a  # green
regular3=d79921  # yellow
regular4=458588  # blue
regular5=b16286  # magenta
regular6=689d6a  # cyan
regular7=a89984  # white

[cursor]
style=block
blink=no

[scrollback]
lines=5000
multiplier=3.0

[url]
launch=xdg-open ${url}
label-letters=sadfjklewcmpgh
osc8-underline=always

[tweak]
# This removes the Noto Sans warning you saw
font-monospace-warn=no
